### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by veasnacheab** [routeviews/issues#110]
### Full Name

NeocomISP

### ASN

9902

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Peer Address(es)

123.108.254.102
2402:5100:0:5::2e

### Multihop

- [X] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by veasnacheab** [comment]
Hi,

I think route-views4.routeviews.org is good enough, please share the bgp parameter to bring up the bgp session.

Thank you!
Veasna

**Comment by pfsinoz** [comment]
Hello Veasna and sorry for the delay while we increased capacity at our University of Oregon collectors.

I've reviewed AS9902's PeeringDB entry and noted that you are also at AMS-IX where we have a RouteViews collector. Would you be interested in peering there in addition to the existing peering at Equinix Singapore? In Singapore I see this right now:
```
Neighbor        V    AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
27.111.228.211  4  9902 2876085   76318        0    0    0 03w5d12h   305347
2001:de8:4::9902:1
                4  9902 2810761   76319        0    0    0 03w5d12h    48194
```
Otherwise we can set up a multihop feed to our new collector.
Please let me know how you'd like to proceed. Thanks!

**Comment by pfsinoz** [comment]
As we have not heard back about creation of the additional peerings requested, I'm closing the case. If you'd still like to proceed, please open a new request.
