### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by erickhuge** [routeviews/issues#120]
### Full Name

Erick Nascimento

### ASN

264409

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [x] Peer at **ALL EXCHANGES** (*and skip the Peer Address(es) field below*)

### Multihop

- [x] Multihop Peering Request

### Code of Conduct (TODO)

- [X] I agree to follow this project's code of conduct

**Comment by pfsinoz** [comment]
Hello Erick, and v sorry for the delay in response due to the lack of capacity we had at our multi-hop collectors at the University of Oregon. We now have a new multi-hop collector in place and can add new peers.

We already peer with AS264409 at Fortaleza, Sao Paulo, Rio de Janeiro, and at FLIX in Florida. We are wondering what extra value would be offered by a multi-hop peering at the University of Oregon?

Thanks for supporting RouteViews!

**Comment by pfsinoz** [comment]
Closing the case now as we have not received any response. If you'd like to set up a multi-hop peering with our collector at the University of Oregon, please open a new request. Thanks!
