### ISSUE TITLE
BGP Timestamp issue for content in Routeviews kafka stream stream.routeviews.org:9092

### ISSUE THREAD

**Issue by ACodingfreak** [routeviews/issues#67]
### Observed Behavior

I am using below bgpreader command on kafka bmp server and filtering all entries from linx

`bgpreader -d kafka -o brokers=stream.routeviews.org:9092 -o topic="^routeviews.*\.bmp_raw" -o data-type=bmp -R "linx" `

As shown in attached file instead of getting sequential timestamped entries I am receiving random updates in between. Is this expected behavior ?

For e.g. BGP UPDATES start at Time 1674024559 then after 20th entry it shifts to 1674024558. Immediately on 33rd entry it is back to Time interval 1674024559. Across the attachment it keeps jumping between 1674024558 and 1674024558. Shouldn't these entries be sequential ?

[01.txt](https://github.com/routeviews/issues/files/10443123/01.txt)

### Expected Behavior

Entries from a router should be sequential and timestamped in an order.

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by kemp-rv** [comment]
> ### Observed Behavior
> 
> I am using below bgpreader command on kafka bmp server and filtering all entries from linx
> 
> `bgpreader -d kafka -o brokers=stream.routeviews.org:9092 -o topic="^routeviews.*\.bmp_raw" -o data-type=bmp -R "linx" `
> 
> As shown in attached file instead of getting sequential timestamped entries I am receiving random updates in between. Is this expected behavior ?
> 
> For e.g. BGP UPDATES start at Time 1674024559 then after 20th entry it shifts to 1674024558. Immediately on 33rd entry it is back to Time interval 1674024559. Across the attachment it keeps jumping between 1674024558 and 1674024558. Shouldn't these entries be sequential ?
> 
> [01.txt](https://github.com/routeviews/issues/files/10443123/01.txt)
> ### Expected Behavior
> 
> Entries from a router should be sequential and timestamped in an order.
> ### Relevant console output or logs
> 
> _No response_
> ### Code of Conduct (TODO)
> 
>     * [x]  I agree to follow this project's Code of Conduct

Just digging through our issues queue.  Sorry for the late response.

To reply, I think what you are seeing here is an artifact of how FRR/bgpd implements the BMP message storage.  

You can check out the FRRouting.org source for bgp_bmp.c
Here's a URL: `https://github.com/FRRouting/frr/blob/master/bgpd/bgp_bmp.c`

So I believe what you see is that when FRR is looping through the message queue, it is looping
through queue-per-peer.  So you will see messages come out in "peer buffered" order.  So for a 
given peer, you will see the increasing timestamps for the point at which the message was received.
But between different peers, you might see jumps varying because of the amount of time it takes to
buffer the messages, and then walk through the peers to write out the buffer.
